'use strict';

const CommercialsPage = {
  async render(container) {
    const [{ data = [] }, { data: vendorMaster = [] }] = await Promise.all([Api.get('/dashboard/commercials'), Api.get('/vendors')]);
    const money = (n) => `INR ${Number(n || 0).toLocaleString('en-IN')}`;
    const client = data.find((c) => c.type === 'client') || { organisation: 'Bharat Forge Ltd', vehicleType: 'sedan', operatingDays: 22, includedTripsPerDay: 3, monthlyRate: 60000, extraTripRate: 900, gstRate: 18 };
    const vendors = data.filter((c) => c.type === 'vendor');
    const legacyVendor = client.vendorCost ? [{ name: 'Primary sedan vendor', organisation: 'Existing vendor contract', vehicleType: client.vehicleType, operatingDays: client.operatingDays, includedTripsPerDay: client.includedTripsPerDay, vendorCost: client.vendorCost, vendorExtraTripRate: client.vendorExtraTripRate, status: 'active' }] : [];
    const mappedVendorRows = vendorMaster.map((v, index) => ({
      name: `${v.name} · Bharat Forge`, organisation: v.name, vehicleType: index % 2 === 0 ? 'sedan' : 'sedan',
      operatingDays: 22, includedTripsPerDay: 3,
      vendorCost: index < 2 ? 48000 : 50000, vendorExtraTripRate: 600,
      status: v.status || 'active', fleetCount: v.vehicleCount || 0,
    }));
    const vendorRows = mappedVendorRows.length ? mappedVendorRows : [...legacyVendor, ...vendors];
    const included = Number(client.operatingDays || 22) * Number(client.includedTripsPerDay || 3);
    const clientGst = Number(client.monthlyRate || 0) * Number(client.gstRate || 18) / 100;
    const vendorTotal = vendorRows.reduce((sum, v) => sum + Number(v.vendorCost || 0), 0);
    const clientTotal = Number(client.monthlyRate || 0) * vendorRows.length;
    const contribution = clientTotal - vendorTotal;
    const vendorTable = vendorRows.map((v) => `<tr><td><strong>${escapeHtml(v.name || 'Vendor rate')}</strong><br><small>${escapeHtml(v.organisation || '')}${v.fleetCount ? ` · ${v.fleetCount} vehicles` : ''}</small></td><td>${escapeHtml(v.vehicleType || '-')}</td><td>${v.operatingDays || 0}</td><td>${v.includedTripsPerDay || 0}</td><td><strong>${money(v.vendorCost)}</strong></td><td>${money(v.vendorExtraTripRate)}</td><td>${money(Number(client.monthlyRate || 0) - Number(v.vendorCost || 0))}</td><td><span class="pill ok">${escapeHtml(v.status || 'active')}</span></td></tr>`).join('');
    const rateRows = data.map((c) => `<tr><td>${escapeHtml(c.type === 'client' ? 'Client receivable' : 'Vendor payable')}<br><small>${escapeHtml(c.name || '')}</small></td><td>${escapeHtml(c.organisation || '')}</td><td>${escapeHtml(c.vehicleType || '-')}</td><td>${money(c.type === 'client' ? c.monthlyRate : c.vendorCost)}</td><td>${money(c.type === 'client' ? c.extraTripRate : c.vendorExtraTripRate)}</td><td>${c.operatingDays || 0} days · ${c.includedTripsPerDay || 0} trips/day</td><td><span class="pill ok">${escapeHtml(c.status || 'active')}</span></td></tr>`).join('');

    container.innerHTML = `<div class="commercials-page">
      <div class="card commercial-hero"><div><span class="eyebrow">CLIENT COMMERCIAL AGREEMENT</span><h2>${escapeHtml(client.organisation)}</h2><p class="desc">One client agreement with multiple operating vendors under the same transport program.</p></div><button class="btn primary" id="new-commercial">+ Add vendor contract</button></div>
      <section class="card commercial-section client-receivable"><div class="card-head"><div><span class="section-kicker client">PARENT CLIENT RATE · UNIQUE</span><h3>${escapeHtml(client.organisation)} client billing</h3><span class="desc">This is the single receivable rate used for every vehicle operated for this client.</span></div></div><div class="card-body"><table class="commercial-detail"><tbody><tr><th>Client</th><td><strong>${escapeHtml(client.organisation)}</strong></td></tr><tr><th>Vehicle category</th><td>${escapeHtml(client.vehicleType)}</td></tr><tr><th>Monthly charge per vehicle</th><td><strong>${money(client.monthlyRate)}</strong> before GST</td></tr><tr><th>Operating commitment</th><td>${client.operatingDays} days · ${client.includedTripsPerDay} trips/day · ${included} trips/month</td></tr><tr><th>Additional trip charge</th><td><strong>${money(client.extraTripRate)}</strong> per trip</td></tr><tr><th>GST</th><td>${client.gstRate}% · ${money(clientGst)} per vehicle/month</td></tr></tbody></table></div></section>
      <section class="card commercial-section vendor-section"><div class="card-head"><div><span class="section-kicker vendor">CHILD VENDOR CONTRACTS · UNDER ${escapeHtml(client.organisation).toUpperCase()}</span><h3>Operating vendor fleet rates</h3><span class="desc">These suppliers serve the same client. Their payable rates may differ independently.</span></div></div><div class="table-wrap"><table class="table commercial-table"><thead><tr><th>Operating vendor</th><th>Vehicle</th><th>Days</th><th>Trips/day</th><th>Vendor monthly payable</th><th>Vendor extra</th><th>Margin against client rate</th><th>Status</th></tr></thead><tbody>${vendorTable}</tbody></table></div></section>
      <section class="card economics-card"><div class="card-head"><div><span class="section-kicker">PORTFOLIO ECONOMICS</span><h3>Current client fleet contribution</h3><span class="desc">Calculated across ${vendorRows.length} vendor vehicle contract${vendorRows.length === 1 ? '' : 's'}.</span></div></div><div class="economics-grid"><div><small>Client receivable base</small><strong>${money(clientTotal)}</strong><span>${vendorRows.length} vehicle${vendorRows.length === 1 ? '' : 's'}</span></div><div><small>Vendor payable base</small><strong>${money(vendorTotal)}</strong><span>Actual vendor schedules</span></div><div class="highlight"><small>Gross contribution</small><strong>${money(contribution)}</strong><span>Before internal overheads</span></div><div class="highlight"><small>Client extra trip</small><strong>${money(client.extraTripRate)}</strong><span>Vendor extra rates vary</span></div></div></section>
      <section class="card"><div class="card-head"><div><h3>${escapeHtml(client.organisation)} commercial register</h3><span class="desc">Parent client billing record and its operating vendor contracts.</span></div></div><div class="table-wrap"><table class="table commercial-table"><thead><tr><th>Level</th><th>Organisation</th><th>Vehicle</th><th>Monthly rate</th><th>Extra trip</th><th>Operating basis</th><th>Status</th></tr></thead><tbody>${rateRows || '<tr><td colspan="7">No commercial records configured.</td></tr>'}</tbody></table></div></section>
      <section class="card" id="commercial-form" hidden><div class="card-head"><div><span class="section-kicker">SETUP</span><h3>Create commercial rate record</h3><span class="desc">Choose Client for the unique receivable schedule or Vendor for a separate payable contract.</span></div></div><div class="card-body"><form id="commercial-create" class="commercial-form-grid"><label>Commercial side<select name="type"><option value="vendor">Vendor payable</option><option value="client">Client receivable</option></select></label><label>Rate card name<input name="name" placeholder="Vendor sedan package" required></label><label>Organisation<input name="organisation" placeholder="Vendor or client name" required></label><label>Vehicle type<select name="vehicleType"><option>sedan</option><option>hatchback</option><option>SUV</option><option>van</option></select></label><div class="form-group-title">Operating commitment</div><label>Operating days / month<input name="operatingDays" type="number" value="22" min="1" required></label><label>Included trips / day<input name="includedTripsPerDay" type="number" value="3" min="0" required></label><div class="form-group-title">Rates</div><label>Vendor monthly payable<input name="vendorCost" type="number" value="48000" min="0"></label><label>Vendor extra trip<input name="vendorExtraTripRate" type="number" value="600" min="0"></label><label>Client monthly receivable<input name="monthlyRate" type="number" value="60000" min="0"></label><label>Client extra trip<input name="extraTripRate" type="number" value="900" min="0"></label><label>GST rate (%)<input name="gstRate" type="number" value="18" min="0"></label><div class="form-actions"><button class="btn ghost" type="button" id="cancel-commercial">Cancel</button><button class="btn primary" type="submit">Save commercial</button></div></form></div></section>
    </div>`;
    document.getElementById('new-commercial').onclick = () => { document.getElementById('commercial-form').hidden = false; document.getElementById('commercial-form').scrollIntoView({ behavior: 'smooth', block: 'start' }); };
    document.getElementById('cancel-commercial').onclick = () => { document.getElementById('commercial-form').hidden = true; };
    document.getElementById('commercial-create').onsubmit = async (e) => { e.preventDefault(); await Api.post('/dashboard/commercials', Object.fromEntries(new FormData(e.target))); this.render(container); };
  },
};
