import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from 'react-native';
import { api, employeeApi, ApiError, clearSession, restoreSession } from './src/api';
import BookingRequests from './src/BookingRequests';

const SMIPL_LOGO = require('./assets-smipl-mark.png');

const C = { ink: '#0b1d2b', navy: '#082238', orange: '#ff651f', blue: '#1678b7', bg: '#f2f6f8', line: '#dce5eb', muted: '#607587', green: '#138a55', red: '#bb2f2f' };
const fmtDate = (v) => v ? new Date(`${v}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' }) : '-';

export default function App() {
  const [ready, setReady] = useState(false); const [signedIn, setSignedIn] = useState(false); const [screen, setScreen] = useState('home');
  const [data, setData] = useState(null); const [requests, setRequests] = useState([]); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const load = async () => { try { const [me, rq] = await Promise.all([employeeApi.me(), employeeApi.requests()]); setData(me); setRequests(rq.data || []); setError(''); } catch (e) { setError(e.message); } };
  const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  useEffect(() => { restoreSession().then((ok) => { setSignedIn(ok); setReady(true); if (ok) load(); }); }, []);
  if (!ready) return <Centered><ActivityIndicator color={C.orange} size="large" /></Centered>;
  if (!signedIn) return <SignIn onDone={() => { setSignedIn(true); load(); }} />;
  const logout = async () => { await clearSession(); setSignedIn(false); setData(null); };
  return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={C.navy} translucent={false} /><View style={[s.header,{paddingTop:38}]}><Text style={s.brand}>SMI Employee</Text><Text style={s.sub}>{data?.organisation || 'PeoplePilot staff app'}</Text></View>
    <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={C.orange} colors={[C.orange]} />}>{error ? <Text style={s.error}>{error}</Text> : null}{screen === 'home' && <Home data={data} onRefresh={refresh} />}{screen === 'trips' && <Trips data={data} />}{screen === 'requests' && <BookingRequests rows={requests} onCreated={load} />}{screen === 'profile' && <Profile data={data} onLogout={logout} />}</ScrollView></KeyboardAvoidingView>
    <View style={s.tabs}>{[['home','Home'],['trips','Trips'],['requests','Requests'],['profile','Profile']].map(([key,label]) => <Pressable key={key} onPress={() => setScreen(key)} style={[s.tab, screen === key && s.tabOn]}><Text style={[s.tabText, screen === key && s.tabTextOn]}>{label}</Text></Pressable>)}</View>
  </SafeAreaView>;
}

function SignIn({ onDone }) { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [busy,setBusy]=useState(false); const [err,setErr]=useState(''); const submit=async()=>{setBusy(true);setErr('');try{await api.login(email.trim().toLowerCase(),password);onDone();}catch(e){setErr(e instanceof ApiError ? e.message : 'Unable to sign in.');}finally{setBusy(false);}}; return <Centered><View style={s.login}><Image source={SMIPL_LOGO} style={s.logoImage} resizeMode="contain"/><Text style={s.loginTitle}>SMIPL User</Text><Text style={s.muted}>Sign in to view your own trips and raise requests.</Text><Text style={s.label}>Email address</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@company.com"/><View style={s.passwordLabel}><Text style={s.label}>Password</Text><Pressable onPress={() => setShowPassword(!showPassword)}><Text style={s.showPassword}>{showPassword ? 'Hide' : 'Show'}</Text></Pressable></View><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry={!showPassword} placeholder="Password"/><Text style={s.hint}>Employee account only. Client and driver accounts use their own applications.</Text>{err ? <Text style={s.error}>{err}</Text> : null}<Pressable style={s.primary} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Sign in</Text>}</Pressable></View></Centered>; }
function Home({ data, onRefresh }) { const e=data?.employee; const trip=data?.upcoming?.[0]; return <><View style={s.welcome}><Text style={s.eyebrow}>MY TRANSPORT</Text><Text style={s.title}>Hello, {e?.name || 'Employee'}</Text><Text style={s.muted}>{e?.department || 'Staff member'} · {e?.code || ''}</Text></View><View style={s.row}><Stat label="Upcoming trips" value={data?.upcoming?.length || 0}/><Stat label="Trip history" value={data?.history?.length || 0}/></View><Card title="Next assigned trip"><Text style={s.big}>{trip ? fmtDate(trip.date) : 'No trip scheduled'}</Text>{trip ? <><Text style={s.body}>{trip.shift?.name || 'Transport'} · {trip.route?.name || 'Route pending'}</Text><Text style={s.body}>Vehicle: {trip.vehicle?.regNo || 'Pending'} · Driver: {trip.driver?.name || 'Pending'}</Text><Text style={s.status}>{trip.status}</Text></> : <Text style={s.muted}>Your transport desk will publish the assignment here.</Text>}</Card><Pressable style={s.secondary} onPress={onRefresh}><Text style={s.secondaryText}>Refresh status</Text></Pressable></>; }
function Trips({ data }) { return <><Text style={s.title}>My trips</Text>{[...(data?.upcoming||[]),...(data?.history||[])].map((t,i)=><Card key={`${t.id}-${i}`} title={`${fmtDate(t.date)} · ${t.status}`}><Text style={s.body}>{t.route?.name || 'Route pending'}</Text><Text style={s.body}>Pickup: {t.booking?.stop || 'Assigned stop'} · Vehicle: {t.vehicle?.regNo || 'Pending'}</Text><Text style={s.body}>Driver: {t.driver?.name || 'Pending'}</Text></Card>)}{!(data?.upcoming?.length||data?.history?.length)&&<Empty text="No trips are assigned yet."/>}</>; }
function Requests({ rows, onCreated }) { const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [pickup,setPickup]=useState(''); const [drop,setDrop]=useState(''); const [notes,setNotes]=useState(''); const [subject,setSubject]=useState(''); const [detail,setDetail]=useState(''); const book=async()=>{try{await employeeApi.bookRide({date,time,pickupPoint:pickup,dropPoint:drop,notes});setDate('');setTime('');setPickup('');setDrop('');setNotes('');await onCreated();Alert.alert('Booking sent','SMIPL will validate and assign the nearest available vehicle and driver.');}catch(e){Alert.alert('Could not book ride',e.message);}}; const send=async()=>{if(subject.trim().length<3)return Alert.alert('Add a subject','Describe what you need help with.');try{await employeeApi.createRequest({subject,detail,category:'other',priority:'normal'});setSubject('');setDetail('');await onCreated();Alert.alert('Request sent','The SMIPL transport desk has received it.');}catch(e){Alert.alert('Could not send',e.message);}};return <><Text style={s.title}>Requests</Text><Card title="Book a ride"><Text style={s.label}>Travel date</Text><TextInput style={s.input} value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/><Text style={s.label}>Pickup time</Text><TextInput style={s.input} value={time} onChangeText={setTime} placeholder="HH:MM"/><Text style={s.label}>Pickup point</Text><TextInput style={s.input} value={pickup} onChangeText={setPickup} placeholder="Home / pickup point"/><Text style={s.label}>Drop point</Text><TextInput style={s.input} value={drop} onChangeText={setDrop} placeholder="Office / destination"/><TextInput style={s.input} value={notes} onChangeText={setNotes} placeholder="Notes (optional)"/><Pressable style={s.primary} onPress={book}><Text style={s.primaryText}>Book ride with SMIPL</Text></Pressable></Card><Card title="Other transport request"><TextInput style={s.input} value={subject} onChangeText={setSubject} placeholder="Subject"/><TextInput style={[s.input,s.multiline]} value={detail} onChangeText={setDetail} placeholder="Details" multiline/><Pressable style={s.secondary} onPress={send}><Text style={s.secondaryText}>Send request</Text></Pressable></Card>{rows.map((r)=><Card key={r.id} title={r.subject}><Text style={s.body}>{r.detail || `${r.pickupPoint || ''} to ${r.dropPoint || ''}`}</Text><Text style={s.status}>{r.status}</Text></Card>)}{!rows.length&&<Empty text="No requests raised."/>}</>; }
function Profile({ data, onLogout }) { return <><Text style={s.title}>Profile</Text><Card title={data?.employee?.name}><Text style={s.body}>{data?.employee?.email || ''}</Text><Text style={s.body}>{data?.organisation || ''}</Text><Text style={s.body}>{data?.employee?.phone || ''}</Text></Card><Pressable style={s.logout} onPress={onLogout}><Text style={s.logoutText}>Sign out</Text></Pressable></>; }
function Card({ title, children }) { return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>; } function Stat({label,value}){return <View style={s.stat}><Text style={s.muted}>{label}</Text><Text style={s.statValue}>{value}</Text></View>;} function Empty({text}){return <View style={s.empty}><Text style={s.muted}>{text}</Text></View>;} function Centered({children}){return <SafeAreaView style={s.center}>{children}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},center:{flex:1,backgroundColor:C.bg,justifyContent:'center',padding:20},header:{backgroundColor:C.navy,paddingHorizontal:20,paddingVertical:16},brand:{color:'#fff',fontSize:22,fontWeight:'800'},sub:{color:'#bdd2e0',marginTop:3},content:{padding:16,paddingBottom:90},welcome:{marginBottom:16},eyebrow:{color:C.orange,fontWeight:'800',letterSpacing:1.5,fontSize:12},title:{fontSize:25,fontWeight:'800',color:C.ink,marginBottom:5},muted:{color:C.muted,fontSize:14},row:{flexDirection:'row',gap:10,marginBottom:12},stat:{flex:1,backgroundColor:'#fff',borderRadius:12,borderWidth:1,borderColor:C.line,padding:14},statValue:{fontSize:28,fontWeight:'800',color:C.blue,marginTop:5},card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:C.line,padding:16,marginBottom:12},cardTitle:{fontSize:17,fontWeight:'800',color:C.ink,marginBottom:10},big:{fontSize:24,fontWeight:'800',color:C.blue,marginBottom:5},body:{fontSize:15,color:C.ink,lineHeight:22},status:{color:C.green,fontWeight:'800',marginTop:10,textTransform:'capitalize'},empty:{padding:20,alignItems:'center'},tabs:{position:'absolute',bottom:0,left:0,right:0,height:68,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:C.line,flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabOn:{borderTopWidth:3,borderTopColor:C.orange},tabText:{fontWeight:'700',color:C.muted},tabTextOn:{color:C.orange},login:{backgroundColor:'#fff',padding:22,borderRadius:18,borderWidth:1,borderColor:C.line},logoImage:{width:150,height:82,marginBottom:14},loginTitle:{fontSize:25,fontWeight:'800',color:C.ink,marginBottom:5},label:{fontSize:13,fontWeight:'700',color:C.ink,marginTop:18,marginBottom:6},passwordLabel:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},showPassword:{color:C.orange,fontWeight:'800',marginTop:18,marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:13,fontSize:16,color:C.ink,backgroundColor:'#fff',marginBottom:8},multiline:{minHeight:90,textAlignVertical:'top'},primary:{backgroundColor:C.orange,borderRadius:10,minHeight:50,justifyContent:'center',alignItems:'center',marginTop:12},primaryText:{color:'#fff',fontWeight:'800',fontSize:16},secondary:{borderWidth:1,borderColor:C.blue,borderRadius:10,minHeight:46,justifyContent:'center',alignItems:'center',marginBottom:12},secondaryText:{color:C.blue,fontWeight:'800'},hint:{color:C.muted,fontSize:12,lineHeight:18,marginTop:12},error:{backgroundColor:'#fde8e8',color:C.red,padding:10,borderRadius:8,marginVertical:10},logout:{backgroundColor:C.navy,borderRadius:10,minHeight:50,alignItems:'center',justifyContent:'center'},logoutText:{color:'#fff',fontWeight:'800',fontSize:16}});
