'use strict';
const app=document.getElementById('app');let state={m:{},staff:[],requests:[],statement:{totals:{}},operations:{trips:[],vehicles:[],drivers:[],incidents:[],documents:[],report:{}}};
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}):'-';
const modules=[['dashboard','📊','Dashboard'],['trips','🚍','Trip Logs'],['requests','📨','Requests'],['tracking','📡','Live Tracking'],['vehicle-kyc','🚗','Vehicle KYC'],['driver-kyc','👤','Driver KYC'],['incidents','🚨','Incidents'],['employees','👥','Employees'],['reports','📈','Reports'],['billing','₹','Billing & Invoicing']];
function buildNav(){document.getElementById('client-nav').innerHTML='<div class="nav-group"><div class="label">CLIENT OPERATIONS</div>'+modules.map(x=>`<button class="nav-item" data-view="${x[0]}"><span class="ico">${x[1]}</span><span>${x[2]}</span></button>`).join('')+'</div>';document.querySelectorAll('#client-nav .nav-item').forEach(x=>x.onclick=()=>render(x.dataset.view));}
function active(v){document.querySelectorAll('#client-nav .nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('page-title').textContent=modules.find(x=>x[0]===v)?.[2]||'Client Dashboard';}
function card(label,value,hint,tone='info'){return `<div class="stat ${tone}"><div class="label">${label}</div><div class="value">${value}</div><div class="foot">${hint}</div></div>`;}
function render(v='dashboard'){active(v);const s=state.statement.totals||{},pending=state.requests.filter(x=>x.status==='pending').length,up=state.m.upcoming||[];
if(v==='dashboard')app.innerHTML=`<div class="grid cols-4 client-kpis">${card('👥 Staff',state.staff.length,'Registered employees','ok')}${card('📨 Open requests',pending,'Awaiting SMIPL review','info')}${card('🚍 Upcoming trips',up.length,'Assigned transport','warn')}${card('🧾 Trips this period',s.trips||0,'Completed service','danger')}</div><div class="card client-flow"><div class="card-head"><div><h3>Client transport workflow</h3><span class="desc">Your request moves to SMIPL for validation, allocation and trip tracking.</span></div><button class="btn sm" data-go="requests">Raise request &rarr;</button></div><div class="client-steps"><b>1<br><span>Request</span><small>Client staff need transport</small></b><b>2<br><span>Review</span><small>SMIPL validates demand</small></b><b>3<br><span>Allocate</span><small>Vehicle and driver assigned</small></b><b>4<br><span>Track</span><small>Live trip status visible</small></b></div></div><div class="card"><div class="card-head"><h3>Upcoming trips</h3><button class="btn sm ghost" data-go="trips">View trips &rarr;</button></div><div class="card-body tight">${up.length?up.map(t=>`<div class="workflow-row"><span class="workflow-dot request"></span><div class="workflow-main"><strong>${date(t.date)} · ${esc(t.routeName||'Ad-hoc trip')}</strong><span>${esc(t.vehicleRegNo||'Vehicle pending')} · ${esc(t.driverName||'Driver pending')}</span></div></div>`).join(''):'<div class="empty"><h4>No upcoming trips</h4><p>Submit a request when your staff need transport.</p></div>'}</div></div>`;
else if(v==='employees')app.innerHTML=`<div class="card"><div class="card-head"><div><h3>Employee register</h3><span class="desc">Staff belonging to your organisation</span></div><button class="btn sm" id="add">+ Register employee</button></div><div class="card-body tight"><table class="table"><thead><tr><th>Name</th><th>Code</th><th>Department</th><th>Pickup stop</th></tr></thead><tbody>${state.staff.map(e=>`<tr><td>${esc(e.name)}</td><td>${esc(e.code||'-')}</td><td>${esc(e.department||'-')}</td><td>${esc(e.stop||'-')}</td></tr>`).join('')||'<tr><td colspan="4">No staff registered.</td></tr>'}</tbody></table></div></div>`;
else if(v==='requests')app.innerHTML=`<div class="card"><div class="card-head"><div><h3>Transport requests</h3><span class="desc">Ad-hoc requirements raised by client staff</span></div><button class="btn sm" data-go="book">+ New request</button></div><div class="card-body tight"><table class="table"><thead><tr><th>Subject</th><th>Category</th><th>Created</th><th>Status</th></tr></thead><tbody>${state.requests.map(r=>`<tr><td>${esc(r.subject)}</td><td>${esc(r.kind||r.category||'Other')}</td><td>${date(r.createdAt?.slice?.(0,10))}</td><td><span class="pill ${r.status==='pending'?'warn':'ok'}">${esc(r.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No requests found.</td></tr>'}</tbody></table></div></div>`;
else if(v==='book')app.innerHTML=`<div class="card"><div class="card-head"><div><h3>Raise transport request</h3><span class="desc">The request goes directly to SMIPL Admin for allocation</span></div></div><div class="card-body"><form id="booking" class="formgrid"><label>Date<input name="date" type="date" required></label><label>Pickup point<input name="pickupPoint" required></label><label>Drop point<input name="dropPoint" required></label><label>Pickup time<input name="time" type="time" required></label><label>Passengers<input name="headcount" type="number" min="1" value="1"></label><label>Priority<select name="priority"><option>normal</option><option>high</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="btn">Send to SMIPL</button></form></div></div>`;
else if(v==='trips'||v==='tracking'){const rows=state.operations.trips||[];app.innerHTML=`<div class="card"><div class="card-head"><div><h3>${v==='tracking'?'Live Tracking':'Trip Logs'}</h3><span class="desc">${v==='tracking'?'Assigned Bharat Forge trips only.':'Scheduled, active and completed trips.'}</span></div></div><div class="card-body tight">${rows.length?`<table class="table"><thead><tr><th>Date</th><th>Trip</th><th>Vehicle</th><th>Driver</th><th>Status</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${date(t.date)}</td><td>${esc(t.id)}</td><td>${esc(t.vehicle?.regNo||'-')}</td><td>${esc(t.driver?.name||'-')}</td><td><span class="pill ${t.status==='completed'?'ok':'info'}">${esc(t.status)}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty"><h4>No client trips yet</h4><p>Assigned trip details will appear after SMIPL allocation.</p></div>'}</div></div>`;}
else if(v==='billing'||v==='reports')app.innerHTML=`<div class="grid cols-4">${card('Trips',s.trips||0,'Service period','info')}${card('Staff journeys',s.staffJourneys||0,'Verified journeys','ok')}${card('Distance',`${s.km||0} km`,'Recorded distance','warn')}${card('Amount',`₹${Number(s.amount||0).toLocaleString('en-IN')}`,'Current statement','danger')}</div><div class="card"><div class="card-head"><h3>${v==='billing'?'Billing & invoicing':'Client reports'}</h3></div><div class="card-body"><p class="muted">Client-level service records are prepared from completed and verified trips. Invoice details are available after SMIPL reconciliation.</p></div></div>`;
else if(v==='vehicle-kyc'||v==='driver-kyc'){const rows=v==='vehicle-kyc'?state.operations.vehicles:state.operations.drivers;app.innerHTML=`<div class="card"><div class="card-head"><h3>${v==='vehicle-kyc'?'Vehicle KYC':'Driver KYC'}</h3><span class="desc">Records assigned to your organisation</span></div><div class="card-body tight"><table class="table"><thead><tr>${v==='vehicle-kyc'?'<th>Registration</th><th>Model</th>':'<th>Driver</th><th>Phone</th>'}<th>Status</th><th>KYC</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(v==='vehicle-kyc'?r.regNo:r.name)}</td><td>${esc(v==='vehicle-kyc'?r.model:r.phone||'-')}</td><td>${esc(r.status)}</td><td><span class="pill ok">${esc(r.kycStatus)}</span></td></tr>`).join(''):'<tr><td colspan="4">No assigned records.</td></tr>'}</tbody></table></div></div>`;}
else if(v==='incidents'){const rows=state.operations.incidents||[];app.innerHTML=`<div class="card"><div class="card-head"><h3>Incidents</h3><span class="desc">Incidents related to your assigned transport</span></div><div class="card-body tight"><table class="table"><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Reported</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.description||r.type||r.id)}</td><td>${esc(r.severity||'normal')}</td><td>${esc(r.status||'open')}</td><td>${date(r.createdAt?.slice?.(0,10))}</td></tr>`).join(''):'<tr><td colspan="4">No incidents for this organisation.</td></tr>'}</tbody></table></div></div>`;}
else app.innerHTML=`<div class="card"><div class="card-head"><h3>${modules.find(x=>x[0]===v)?.[2]}</h3><span class="desc">Read-only client visibility</span></div><div class="card-body"><div class="empty"><h4>No records available</h4><p>SMIPL controls this operational module. Client-visible records will appear here when applicable.</p></div></div></div>`;
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>render(x.dataset.go));document.getElementById('add')?.addEventListener('click',async()=>{const name=prompt('Employee name'),email=prompt('Employee email');if(name&&email){await Api.post('/mobile/client/staff',{name,email,password:'Welcome@2026',department:'Operations'});boot();}});document.getElementById('booking')?.addEventListener('submit',async e=>{e.preventDefault();const r=await Api.post('/mobile/client/booking-requests',Object.fromEntries(new FormData(e.target)));alert(r.message||'Request sent to SMIPL.');boot();});}
async function boot(){try{const me=await Api.get('/auth/me');if(!['client','operations'].includes(me.user.role))throw Error('Client account required');const [m,staff,requests,statement,operations]=await Promise.all([Api.get('/mobile/client/me'),Api.get('/mobile/client/roster'),Api.get('/mobile/client/requests'),Api.get('/mobile/client/statement'),Api.get('/mobile/client/operations')]);state={m,staff:staff.data||[],requests:requests.data||[],statement,operations};document.getElementById('org-name').textContent=m.organisation||me.user.organisation;document.getElementById('sidebar-org').textContent=m.organisation||me.user.organisation;buildNav();render('dashboard');}catch(e){app.innerHTML=`<div class="card"><div class="empty"><h4>Unable to load client workspace</h4><p>${esc(e.message)}</p></div></div>`;}}
document.getElementById('signout').onclick=()=>{Api.clearToken();location.href='/smipl/login.html?fresh=1';};boot();
Api.get('/mobile/client/me').then(m=>{const name=m.organisation||'Client organisation';const title=document.querySelector('.sidebar-head .title');const org=document.getElementById('org-name');const foot=document.getElementById('sidebar-org');if(title)title.textContent=name;if(org)org.textContent=name;if(foot)foot.textContent=name;const mark=document.querySelector('.sidebar-head .mark');if(mark){mark.innerHTML=m.branding?.logoUrl?`<img src="${esc(m.branding.logoUrl)}" alt="${esc(name)} logo">`:`<span class="client-initials">${esc(name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</span>`;}document.documentElement.style.setProperty('--client-brand',m.branding?.primaryColor||'#f4511e');}).catch(()=>{});
