'use strict';
(() => {
  const stages=[['01','Demand','Client request'],['02','Validate','Policy check'],['03','Plan','Route clubbing'],['04','Allocate','Vehicle + driver'],['05','Dispatch','Alerts + manifest'],['06','Execute','GPS + boarding'],['07','Verify','Safe drop + close'],['08','Bill','Reconcile + invoice']];
  const state={role:'client',stage:0,log:[]};
  const actions=[
    {title:'Submit transport demand',desc:'Create a realistic client request for employee transport.',html:`<div class="form"><div class="field"><label>Travel date</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Shift</label><select id="shift"><option>General Shift · 09:00</option><option>Shift 1 · 06:30</option><option>Night Shift · 22:00</option></select></div><div class="field"><label>Employees travelling</label><input id="count" type="number" value="6" min="1"></div><div class="field"><label>Priority</label><select id="priority"><option>Normal</option><option>High - safety sensitive</option></select></div><div class="field"><label>Pickup area</label><input id="pickup" value="Hinjawadi Phase 1"></div><div class="field"><label>Destination</label><input id="drop" value="SMIPL Plant 2"></div><div class="field full"><label>Safety preference</label><input id="safety" value="Verified driver and live ETA"></div></div>`,button:'Submit demand'},
    {title:'Validate and approve',desc:'SMIPL checks the demand before planning.',html:`<div class="notice">Policy checks passed: active staff, valid shift, serviceable pickup area and approved destination.</div><div class="kv"><span>Validation owner</span><b>SMIPL Operations</b></div><div class="kv"><span>Demand decision</span><b>Approved for planning</b></div>`,button:'Approve and plan route'},
    {title:'Plan route and club demand',desc:'The system groups employees by time and geography.',html:`<div class="kv"><span>Cluster</span><b>Hinjawadi - Wakad</b></div><div class="kv"><span>Stops</span><b>6 employee stops + plant</b></div><div class="kv"><span>Plan</span><b>Mini-car route · 18.4 km</b></div>`,button:'Publish allocation'},
    {title:'Allocate vehicle and driver',desc:'Availability, capacity, compliance and vendor performance are checked.',html:`<div class="kv"><span>Vendor</span><b>SMIPL approved vendor</b></div><div class="kv"><span>Vehicle</span><b>MH-12-AB-4521 · Mini-car · 6 seats</b></div><div class="kv"><span>Driver</span><b>Ramesh Sawant · verified</b></div>`,button:'Dispatch trip'},
    {title:'Dispatch trip',desc:'The client and employees receive the assignment details.',html:`<div class="notice success">Trip TRP-SIM-001 is published. Employee alerts and driver manifest are ready.</div><div class="kv"><span>Pickup window</span><b>08:10 - 08:25</b></div><div class="kv"><span>Notification</span><b>Client + 6 employees + driver</b></div>`,button:'Driver accepts assignment'},
    {title:'Execute trip',desc:'Driver starts, shares GPS and records boarding milestones.',html:`<div class="kv"><span>Trip state</span><b>In progress · GPS reporting</b></div><div class="kv"><span>Boarding</span><b>6 / 6 employees boarded</b></div><div class="kv"><span>Safety</span><b>No SOS, speeding or geofence alert</b></div>`,button:'Confirm safe drop'},
    {title:'Verify and close trip',desc:'Safe drop, final odometer and notes make the trip billable.',html:`<div class="notice success">All passengers safely dropped. Driver submitted final odometer and trip notes.</div><div class="kv"><span>Distance</span><b>19.1 km actual</b></div><div class="kv"><span>Trip status</span><b>Completed and verified</b></div>`,button:'Generate billing record'},
    {title:'Reconcile and invoice',desc:'The completed trip is reconciled against the configured rate card.',html:`<div class="kv"><span>Rate basis</span><b>Contracted mini-car trip rate</b></div><div class="kv"><span>Billable trip</span><b>TRP-SIM-001 · verified</b></div><div class="kv"><span>Commercial status</span><b>Invoice ready for review</b></div><div class="notice success">Workflow complete. The record is available for reports and audit.</div>`,button:'Start another simulation'}
  ];
  function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function render(){
    document.querySelector('.mode').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.role===state.role));
    document.querySelector('#flow').innerHTML=stages.map((s,i)=>`<div class="step ${i<state.stage?'done':''} ${i===state.stage?'current':''}"><b>${s[0]}</b><strong>${s[1]}</strong><small>${s[2]}</small></div>`).join('');
    const a=actions[state.stage]; document.querySelector('#panel').innerHTML=`<span class="eyebrow">${state.role==='client'?'CLIENT WORKSPACE':state.role==='admin'?'SMIPL ADMIN WORKSPACE':'DRIVER WORKSPACE'}</span><h2>${a.title}</h2><p>${a.desc}</p>${a.html}<div class="actions"><button class="primary" id="next">${a.button}</button>${state.stage>0?'<button class="secondary" id="back">Back</button>':''}</div>`;
    document.querySelector('#statusText').textContent=state.stage<8?stages[state.stage][1]:'Complete'; document.querySelector('#statusSub').textContent=state.stage<8?`Step ${state.stage+1} of 8 · ${stages[state.stage][2]}`:'Ready for reporting and audit';
    document.querySelector('#record').innerHTML=`<div class="kv"><span>Client</span><b>SMIPL</b></div><div class="kv"><span>Served organisations</span><b>Bharat Forge / Kirloskar</b></div><div class="kv"><span>Request</span><b>REQ-SIM-001</b></div><div class="kv"><span>Trip</span><b>TRP-SIM-001</b></div><div class="kv"><span>Current role</span><b>${state.role==='client'?'Client':state.role==='admin'?'SMIPL Admin':'Driver'}</b></div>`;
    document.querySelector('#log').innerHTML=state.log.length?state.log.map(x=>`<div class="event"><b>${esc(x[0])}</b><small>${esc(x[1])}</small></div>`).join(''):'<div class="event">No actions yet<small>Start by submitting a client transport demand.</small></div>';
    document.querySelector('#next').onclick=()=>{if(state.stage===7){state.log.push(['Invoice ready','Trip reconciled and available for billing review']);state.stage=0;state.log.push(['New simulation','Ready for another booking']);state.role='client'}else{state.log.push([stages[state.stage][1],a.title+' completed']);state.stage++;state.role=state.stage<2?'client':state.stage<5?'admin':'driver'}render()};
    const back=document.querySelector('#back');if(back)back.onclick=()=>{state.stage=Math.max(0,state.stage-1);render()};
  }
  document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.role=b.dataset.role;render()}); document.querySelector('#reset').onclick=()=>{state.stage=0;state.log=[];state.role='client';render()}; render();
})();
