import React, { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import * as Location from 'expo-location';
import { WebView } from 'react-native-webview';
import { employeeApi } from './api';

const C = { ink: '#0b1d2b', orange: '#ff651f', blue: '#1678b7', muted: '#607587', line: '#dce5eb', green: '#138a55' };
const fmtDate = (d) => d.toISOString().slice(0, 10);
const fmtTime = (d) => d.toTimeString().slice(0, 5);

export default function BookingRequests({ rows, onCreated }) {
  const [date, setDate] = useState(new Date());
  const [time, setTime] = useState(new Date());
  const [picker, setPicker] = useState(null);
  const [point, setPoint] = useState(null);
  const [pickup, setPickup] = useState(null);
  const [drop, setDrop] = useState(null);
  const [locationText, setLocationText] = useState('');
  const [busy, setBusy] = useState(false);
  const choosePoint = async (kind) => { if (kind === 'current') { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return Alert.alert('Location permission needed', 'Allow location access to use your current pickup point.'); const loc = await Location.getCurrentPositionAsync({}); setPickup({ latitude: loc.coords.latitude, longitude: loc.coords.longitude, label: 'Current location' }); setPoint(null); } catch (e) { Alert.alert('Location unavailable', 'Enter the pickup address instead.'); } return; } setLocationText(''); setPoint(kind); };
  const confirmLocation = () => { const label = locationText.trim(); if (!label) return Alert.alert('Enter a location', 'Type a pickup or drop location.'); const value = { label, latitude: 0, longitude: 0 }; point === 'pickup' ? setPickup(value) : setDrop(value); setPoint(null); };
  const selectMapPoint = () => { const value = { label: 'Map location selected', latitude: 18.5913, longitude: 73.7389 }; point === 'pickup' ? setPickup(value) : setDrop(value); setPoint(null); };
  const book = async () => { if (!pickup || !drop) return Alert.alert('Select locations', 'Choose both pickup and drop points on the map.'); setBusy(true); try { await employeeApi.bookRide({ date: fmtDate(date), time: fmtTime(time), pickupPoint: pickup.label || `${pickup.latitude},${pickup.longitude}`, dropPoint: drop.label || `${drop.latitude},${drop.longitude}`, pickupLatitude: pickup.latitude, pickupLongitude: pickup.longitude, dropLatitude: drop.latitude, dropLongitude: drop.longitude }); await onCreated(); Alert.alert('Booking submitted', 'Your request is now with the SMIPL transport desk.'); } catch (e) { Alert.alert('Booking failed', e.message); } finally { setBusy(false); } };
  return <><Text style={s.title}>Book a ride</Text><Text style={s.muted}>Select your schedule and locations. SMIPL will validate the request and assign the nearest available vehicle and driver.</Text><View style={s.card}><Text style={s.cardTitle}>Travel schedule</Text><Pressable style={s.field} onPress={() => setPicker('date')}><Text style={s.label}>Date</Text><Text style={s.value}>{date.toLocaleDateString('en-IN', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' })}</Text></Pressable><Pressable style={s.field} onPress={() => setPicker('time')}><Text style={s.label}>Pickup time</Text><Text style={s.value}>{fmtTime(time)}</Text></Pressable>{picker && <DateTimePicker value={picker === 'date' ? date : time} mode={picker} minimumDate={picker === 'date' ? new Date() : undefined} onChange={(_, selected) => { setPicker(null); if (selected) picker === 'date' ? setDate(selected) : setTime(selected); }} />}</View><View style={s.card}><Text style={s.cardTitle}>Pickup and drop</Text><Pressable style={s.location} onPress={() => choosePoint('pickup')}><Text style={s.locationTitle}>Pickup point</Text><Text style={s.locationValue}>{pickup?.label || 'Choose pickup location'}</Text></Pressable><Pressable style={s.location} onPress={() => choosePoint('drop')}><Text style={s.locationTitle}>Drop point</Text><Text style={s.locationValue}>{drop?.label || 'Choose drop location'}</Text></Pressable><Pressable style={s.current} onPress={() => choosePoint('current')}><Text style={s.currentText}>Use my current location as pickup</Text></Pressable></View><Pressable style={[s.primary, busy && { opacity: 0.6 }]} disabled={busy} onPress={book}><Text style={s.primaryText}>{busy ? 'Submitting...' : 'Submit booking request'}</Text></Pressable><Text style={s.section}>My booking requests</Text>{rows.map((r) => <View style={s.history} key={r.id}><Text style={s.historyTitle}>{r.subject || 'Employee ride booking'}</Text><Text style={s.muted}>{r.pickupPoint || '-'} → {r.dropPoint || '-'}</Text><Text style={s.status}>{r.status || 'pending'}</Text></View>)}{!rows.length && <Text style={s.muted}>No booking requests yet.</Text>}<Modal visible={Boolean(point)} animationType="slide" onRequestClose={() => setPoint(null)}><View style={s.mapWrap}><Text style={s.mapTitle}>{point === 'pickup' ? 'Pickup' : 'Drop'} location</Text><WebView style={s.map} source={{ uri: 'https://www.openstreetmap.org/export/embed.html?bbox=73.68%2C18.54%2C73.80%2C18.64&layer=mapnik' }} onMessage={selectMapPoint} originWhitelist={['*']} /><TextInput style={s.locationInput} value={locationText} onChangeText={setLocationText} placeholder="Or type a landmark"/><Pressable style={s.primary} onPress={confirmLocation}><Text style={s.primaryText}>Use typed location</Text></Pressable><Pressable style={s.cancel} onPress={() => setPoint(null)}><Text style={s.cancelText}>Cancel</Text></Pressable></View></Modal></>;
}
const s = StyleSheet.create({ title:{fontSize:25,fontWeight:'800',color:C.ink,marginBottom:6},muted:{fontSize:14,color:C.muted,lineHeight:21},card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:C.line,padding:16,marginTop:14},cardTitle:{fontSize:17,fontWeight:'800',color:C.ink,marginBottom:10},field:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:12,marginTop:9},label:{fontSize:12,fontWeight:'700',color:C.muted},value:{fontSize:16,fontWeight:'700',color:C.ink,marginTop:4},location:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:13,marginTop:10},locationTitle:{fontSize:13,fontWeight:'800',color:C.ink},locationValue:{fontSize:15,color:C.blue,marginTop:4},current:{borderRadius:10,backgroundColor:'#eaf6fc',padding:13,marginTop:10},currentText:{color:C.blue,fontWeight:'800',textAlign:'center'},primary:{backgroundColor:C.orange,borderRadius:10,minHeight:52,alignItems:'center',justifyContent:'center',marginTop:14},primaryText:{color:'#fff',fontSize:16,fontWeight:'800'},section:{fontSize:19,fontWeight:'800',color:C.ink,marginTop:24,marginBottom:8},history:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:12,padding:14,marginBottom:9},historyTitle:{fontSize:16,fontWeight:'800',color:C.ink},status:{fontWeight:'800',color:C.green,marginTop:7,textTransform:'capitalize'},mapWrap:{flex:1,backgroundColor:'#fff',paddingTop:45,paddingHorizontal:18},mapTitle:{fontSize:20,fontWeight:'800',color:C.ink,paddingBottom:12},locationInput:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:13,fontSize:16,marginTop:18},cancel:{marginTop:16,borderWidth:1,borderColor:C.line,borderRadius:10,padding:14,alignItems:'center'},cancelText:{color:C.ink,fontWeight:'800'}});
